name: Update video posts
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest video posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: YOUTUBECNA
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCsMica-v34Irf9KVTh6xx-g"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: YOUTUBEPOWER
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCgc3NEslE8oISOEawhcpMCA"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: YOUTUBEGITHUB
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCSgzRJMqIiCNtoM6Q7Q9Lqw"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: YOUTUBEAPPMOD
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCsMica-v34Irf9KVTh6xx-g"
